markdown: kramdown
title: chem-bla-ics
author:
  name: Egon Willighagen
  orcid: 0000-0001-7542-0286
description: Chemblaics (pronounced chem-bla-ics) is the science that uses open science and computers to solve problems in chemistry, biochemistry and related fields.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://egonw.github.io" # the base hostname & protocol for your site, e.g. http://example.com
mastodon:
  username: egonw
  instance: social.edu.nl
mastodon:
  username: egonw
  instance: mastodon.social
social:
  - title: GitHub
    platform: github
    user_url: https://github.com/egonw
  - title: Google Scholar
    platform: google_scholar
    user_url: https://scholar.google.com/citations?user=u8SjMZ0AAAAJ
  - title: Mastodon
    platform: mastodon
    user_url: https://social.edu.nl/@egonw
  - title: LinkedIn
    platform: linkedin
    user_url: https://www.linkedin.com/in/egon-willighagen/
#  orcid: 0000-0001-7542-0286

# Build settings
theme: minima
paginate: 7
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll/mastodon_webfinger
  - jekyll-paginate

feed:
  tags: true

tags:
